apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: agentlauncher
spec:
  selector:
    app: nats
  ports:
  - name: client
    port: 4222
    targetPort: 4222
  - name: monitor
    port: 8222
    targetPort: 8222
  clusterIP: None