apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-launcher
  namespace: agentlauncher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agent-launcher
  template:
    metadata:
      labels:
        app: agent-launcher
    spec:
      containers:
      - name: agent-launcher
        image: agentlauncher/agent-launcher:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: agentlauncher-config
              key: NATS_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5