apiVersion: v1
kind: Service
metadata:
  name: agent-launcher
  namespace: agentlauncher
spec:
  selector:
    app: agent-launcher
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP