apiVersion: apps/v1
kind: Deployment
metadata:
  name: tool-runtime
  namespace: agentlauncher
spec:
  replicas: 5
  selector:
    matchLabels:
      app: tool-runtime
  template:
    metadata:
      labels:
        app: tool-runtime
    spec:
      containers:
      - name: tool-runtime
        image: agentlauncher/tool-runtime:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        env:
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: agentlauncher-config
              key: NATS_URL
        - name: PORT
          value: "8082"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5